### ISSUE TITLE
An option to open the english wiki

### ISSUE THREAD

**Issue by salutre** [BasicallyIAmFox/Wikithis#10]
The english wiki has more pages and informations than the wiki of my native language (french). Can you please add an option to always open the english wiki ?

**Comment by BasicallyIAmFox** [comment]
Yes, I will absolutely try my best to add this feature!

**Comment by salutre** [comment]
If I open the game in english, then change to french, the setting "Always open English wikis" work properly.
However If I open the game in french, it doesn't work.

**Comment by BasicallyIAmFox** [comment]
> If I open the game in english, then change to french, the setting "Always open English wikis" work properly. However If I open the game in french, it doesn't work.

That's really really weird, cause for some reason for me it worked first few times... then gave up???

**Comment by salutre** [comment]
I've deactivated all the other mods I had btw

**Comment by BasicallyIAmFox** [comment]
@salutre can you try out this version?
[Wikithis.zip](https://github.com/BasicallyIAmFox/Wikithis/files/13452545/Wikithis.zip)

**Comment by salutre** [comment]
It works great for vanilla ! 

But it conflicts with a translation mod for calamity, is there an easy fix for that ?
My ultimate goal would be to play calamity with a translation mod, and your wiki mod redirecting me to the english version of calamity's wiki

**Comment by BasicallyIAmFox** [comment]
> It works great for vanilla !
> 
> But it conflicts with a translation mod for calamity, is there an easy fix for that ? My ultimate goal would be to play calamity with a translation mod, and your wiki mod redirecting me to the english version of calamity's wiki

that kinda contradicts with your initial point lol. either way, i don't think there's a way to do that on my side without having to do some cursed stuff (i don't want to do that)
you'd have to ask translation mod's team for that
(unless i find a way to detect translations...)

**Comment by salutre** [comment]
Thank you very much for adding the option as requested !
