### ISSUE TITLE
Mod Does not Load on Stable Latest tModLoader Version

### ISSUE THREAD

**Issue by RoY7x** [BasicallyIAmFox/Wikithis#12]
Currently using tModLoader 2023.10.3.0 and the mod fails to load when enabled due to version issues. Will this be updated to the latest stable release of tModLoader? 
![image_2024-01-01_195650355](https://github.com/BasicallyIAmFox/Wikithis/assets/24259781/653e9e28-ffcb-4358-bddf-d89c2300cd82)

**Comment by BasicallyIAmFox** [comment]
report to devs of MultiverseRel
