### ISSUE TITLE
Pressing the keybind to open the wiki for my mod opens my file explorer

### ISSUE THREAD

**Issue by TheEternalAce** [BasicallyIAmFox/Wikithis#8]
(Title)
Code to add WikiThis support:
```
ModLoader.TryGetMod("Wikithis", out Mod wikithis);
if (wikithis != null)
{
    wikithis.Call("AddModURL", Instance, "terrariamods.wiki.gg/wiki/Shards_of_Atheria/{}");

    // If you want to replace default icon for your mod, then call this. Icon should be 30x30, either way it will be cut.
    wikithis.Call("AddWikiTexture", Instance, ModContent.Request<Texture2D>("ShardsOfAtheria/icon_small"));
}
```
Browser is OperaGX

**Comment by TheEternalAce** [comment]
Update: Works fine using Steam Overlay.

**Comment by BasicallyIAmFox** [comment]
shouldn't it be `wikithis.Call("AddModURL", Instance, "https://terrariamods.wiki.gg/wiki/Shards_of_Atheria/{}");` instead of `wikithis.Call("AddModURL", Instance, "terrariamods.wiki.gg/wiki/Shards_of_Atheria/{}");`?

**Comment by BasicallyIAmFox** [comment]
@TheEternalAce

**Comment by TheEternalAce** [comment]
@BasicallyIAmFox
Your examples have the https thing so that's what I did.

**Comment by BasicallyIAmFox** [comment]
> @BasicallyIAmFox Your examples have the https thing so that's what I did.

you clearly didn't
![image](https://github.com/BasicallyIAmFox/Wikithis/assets/65787578/beded4cb-16a2-4f23-9fc0-598e151a0a95)

**Comment by BasicallyIAmFox** [comment]
@TheEternalAce

**Comment by TheEternalAce** [comment]
agony

**Comment by TheEternalAce** [comment]
it's working now
